export var sportsList = [
	{ value: 'archery', label: 'Archery' },
	{ value: 'athletics/track-field', label: 'Athletics/Track Field' },
	{ value: 'badminton', label: 'Badminton' },
	{ value: 'basketball', label: 'Basketball' },
	{ value: 'billiards-and-snooker', label: 'Billiards and Snooker' },
	{ value: 'boxing', label: 'Boxing' },
	{ value: 'carrom', label: 'Carrom' },
	{ value: 'chess', label: 'Chess' },
	{ value: 'cricket', label: 'Cricket' },
	{ value: 'cycling', label: 'Cycling' },
	{ value: 'equestrian', label: 'Equestrian' },
	{ value: 'fencing', label: 'Fencing' },
	{ value: 'football', label: 'Football' },
	{ value: 'golf', label: 'Golf' },
	{ value: 'gymnastics', label: 'Gymnastics' },
	{ value: 'hockey', label: 'Hockey' },
	{ value: 'kabaddi', label: 'Kabaddi' },
	{ value: 'kho-kho', label: 'Kho Kho' },
	{ value: 'martial-arts', label: 'Martial Arts' },
	{ value: 'motorsports', label: 'Motorsports' },
	{ value: 'polo', label: 'Polo' },
	{ value: 'rowing', label: 'Rowing' },
	{ value: 'sailing', label: 'Sailing' },
	{ value: 'shooting', label: 'Shooting' },
	{ value: 'swimming', label: 'Swimming' },
	{ value: 'squash', label: 'Squash' },
	{ value: 'table-tennis', label: 'Table Tennis' },
	{ value: 'tennis', label: 'Tennis' },
	{ value: 'volleyball', label: 'Volleyball' },
	{ value: 'weightlifting', label: 'Weightlifting' },
	{ value: 'wrestling', label: 'Wrestling' },
	{ value: 'yoga', label: 'Yoga' }
];

export var hobbies = [
	{ value: 'adventure-and-outdoor-activities', label: 'Adventure and Outdoor Activities' },
	{ value: 'arts-and-crafts', label: 'Arts and Crafts' },
	{ value: 'collecting-antiques-or-coins', label: 'Collecting Antiques or Coins' },
	{ value: 'community-service', label: 'Community Service' },
	{ value: 'cooking', label: 'Cooking' },
	{ value: 'cycling-and-trekking', label: 'Cycling and Trekking' },
	{ value: 'dancing', label: 'Dancing' },
	{ value: 'diy-projects-and-home-decor', label: 'DIY Projects and Home Decor' },
	{ value: 'fashion-and-styling', label: 'Fashion and Styling' },
	{ value: 'fitness-and-yoga', label: 'Fitness and Yoga' },
	{ value: 'food-and-dining', label: 'Food and Dining' },
	{ value: 'gaming', label: 'Gaming' },
	{ value: 'gardening', label: 'Gardening' },
	{ value: 'hiking-and-nature-walks', label: 'Hiking and Nature Walks' },
	{ value: 'learning-new-languages', label: 'Learning New Languages' },
	{ value: 'meditation-and-spirituality', label: 'Meditation and Spirituality' },
	{ value: 'movies-and-theatre', label: 'Movies and Theatre' },
	{ value: 'music', label: 'Music' },
	{ value: 'painting', label: 'Painting' },
	{ value: 'pets-and-animal-care', label: 'Pets and Animal Care' },
	{ value: 'photography', label: 'Photography' },
	{ value: 'reading', label: 'Reading' },
	{ value: 'singing', label: 'Singing' },
	{ value: 'sports', label: 'Sports' },
	{ value: 'social-causes-and-volunteering', label: 'Social Causes and Volunteering' },
	{ value: 'teaching-and-mentoring', label: 'Teaching and Mentoring' },
	{ value: 'technology-and-gadgets', label: 'Technology and Gadgets' },
	{ value: 'travelling', label: 'Travelling' },
	{ value: 'writing-and-poetry', label: 'Writing and Poetry' },
	{ value: 'writing-blogs-or-articles', label: 'Writing Blogs or Articles' }
];

export var diseases = [
	'allergy',
	'chronic pain',
	'digestive disorders',
	'mental health',
	'others'
];
